### ISSUE TITLE
Bug: Discounts and Gifts Not Updating in Checkout Details Until Checkout Session Expires 

### ISSUE THREAD

**Issue by LeenaSomanS** [saleor/saleor#15789]
### What are you trying to achieve?

During checkout creation, discounts and gifts are automatically applied. If an admin makes changes to discounts, the checkout details continue to display the previous information, including old gifts and discounts until the checkout session expires or the user modifies the cart by adding or removing items, changing delivery methods, or applying vouchers.
**Related Issue: A similar issue has been raised by another user in a discussion thread: #14617**

### Steps to reproduce the problem

1. Create a checkout session with applied discounts.
2. As an admin, make changes to discounts such as deleting certain rules or altering prices.
3. Observe that the changes are not immediately reflected in the checkout details.

### What did you expect to happen?

**Expected Behavior:**
Changes made by the admin to discounts, gifts, shipping methods, or vouchers should be immediately reflected in the checkout details without requiring the checkout session to end or user cart modifications.

### Logs

1.Promotion details
![Screenshot from 2024-04-15 12-28-00](https://github.com/saleor/saleor/assets/68951116/f6afd7e2-a937-4805-95e5-6179646b0541)
2.Creating a checkout with eligible gifts based on promotion rules.
![Screenshot from 2024-04-15 12-49-07](https://github.com/saleor/saleor/assets/68951116/f8666ca6-0a00-4654-afe8-201c378a0056)

3. The admin removed the gift and applied a subtotal discount instead.
![Screenshot from 2024-04-15 12-31-59](https://github.com/saleor/saleor/assets/68951116/4e8de335-5723-416c-bcb8-78d6d988b4da)
4. Discounts remain unchanged in checkout details despite modifications.
![Screenshot from 2024-04-15 12-43-58](https://github.com/saleor/saleor/assets/68951116/71c7d186-01ba-4999-b1a9-8735c7bb2ce2)
 

### Environment

Saleor version: 3.19

**Comment by SarthakNikhal** [comment]
@LeenaSomanS Can I work on this issue?

**Comment by SarthakNikhal** [comment]
@IKarbowiak Is this fixed in the current release?

**Comment by IKarbowiak** [comment]
Hi @SarthakNikhal,
I'm not sure but I think that it wasn't fixed.

Regarding the issue, we are probably missing the marking the checkout prices should be refreshed but needs further investigation.

**Comment by leena-valoriz** [comment]
@IKarbowiak @maarcingebala Could you both propose a solution for this?  I've tried to reduce the checkout expiration time, but it's not functioning as expected.

**Comment by leena-valoriz** [comment]
@IKarbowiak @maarcingebala Could you both propose a solution for this? I've tried to reduce the checkout expiration time, but it's not functioning as expected.

**Comment by LeenaSomanS** [comment]
@IKarbowiak @maarcingebala Could you both propose a solution for this? I've tried to reduce the checkout expiration time, but it's not functioning as expected.

**Comment by aniav** [comment]
This has been addressed and fixed in 3.18.70 and all the newer versions. Feel free to reopen if it happens again 🙌
